homeassistant:
  name: Rodnik-2-45
  latitude: 56.108084
  longitude: 38.497180
  elevation: 160
  unit_system: metric
  time_zone: Europe/Moscow

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate

#Вынос во внешние файлы
group:      !include includes/groups.yaml
automation: !include includes/automations.yaml
script:     !include includes/scripts.yaml
scene:      !include includes/scenes.yaml
recorder:   !include includes/recorder.yaml

#Вынос во внешние папки
sensor: !include_dir_merge_list includes/sensors
