homeassistant:
  name: Rodnik-2-45
  latitude:  !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Moscow

#  customize: !include customize.yaml
  
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate

#Вынос во внешние файлы
group:      !include includes/groups.yaml
script:     !include includes/scripts.yaml
scene:      !include includes/scenes.yaml
recorder:   !include includes/recorder.yaml

#Вынос во внешние папки
sensor:     !include_dir_merge_list includes/sensors
automation: !include_dir_merge_list includes/automations

rest_command:
  hassio_google_backup:
    url: !secret hassio_google_backup_url