title: Home Assistant -- Docn Lab
views:

  - title: Главная
    icon: mdi:home-assistant
    
    cards:
    
      - type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.time
            name: Текущее время
            icon: mdi:clock-outline
          - entity: sensor.date
            name: Текущее время
            icon: mdi:calendar
            
      - type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.maria_db_size
            name: Размер БД
            icon: mdi:database

      - type: history-graph
        entities:
          - entity: sensor.maria_db_size
            name: Maria DB

      - type: horizontal-stack
        cards:
          - type: gauge
            name: CPU
            unit: '%'
            entity: sensor.processor_use
            severity:
              green: 0
              yellow: 60
              red: 85
          - type: gauge
            name: RAM
            unit: '%'
            entity: sensor.memory_use_percent
            severity:
              green: 0
              yellow: 70
              red: 90

      - type: horizontal-stack
        cards:
          - type: gauge
            name: HDD
            unit: '%'
            entity: sensor.disk_use_percent
            severity:
              green: 0
              yellow: 4
              red: 80
          - type: gauge
            name: Свободно на диске
            unit: 'Гб'
            entity: sensor.disk_free
            severity:
              green: 12
              yellow: 7
              red: 2
            
  - title: Погода
    icon: mdi:weather-partly-snowy-rainy
    cards:

        - type: weather-forecast
          entity: weather.home_assistant 
